export { default as Topbar } from "./topbar/Topbar";
export { default as Intro } from "./intro/Intro";
export { default as Portfolio } from "./portfolio/Portfolio";
export { default as Testimonials } from "./testimonials/Testimonials";
export { default as Work } from "./work/Work";
export { default as Contacts } from "./contacts/Contacts";
export { default as Menu } from "./menu/Menu";
export { default as PortfolioCats } from "./portfolioCats/PortfolioCats";
export { default as Footer } from "./footer/Footer";
